project:
  type: website
  output-dir: docs

website:
  title: "TDS"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      light: 
        - flatly
      dark:
        - sketchy
    css: styles.css
    toc: true



