project:
  type: website
  output-dir: docs

website:
  title: "TDS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "./OsBoot/osboot.qmd"
        text: "OS Boot"

format:
  html:
    theme:
      light: 
        - flatly
      dark:
        - sketchy
    css: styles.css
    toc: true



