# Dual-Boot Setup Guide

This guide will help you install another operating system (Linux) alongside your existing Windows installation.

::: {.callout-note collapse="False"}  
# Disclaimer
`Do this at your own risk.` Please watch various YouTube videos and proceed with dual boot only when you are 100% sure about the process.

If you want to minimize the risk:  
1. **Use External SSD/HDD** to install Linux    
    - This will prevent almost 99% of any accidental damage to your main system  
2. **Install Kubuntu**    
    - Since dual boot requires creating partitions  
    - Kubuntu has a `Replace Partition` option which avoids most of the headache  

:::




## Requirements
1. New SSD/HDD or at least 30GB free storage on your current Windows drive
    - If installing on the same SSD/HDD where Windows is installed:
    - I recommend shrinking at least a 30GB partition
        - [How To Shrink Partition](https://youtu.be/eJYwbqlAMd4?si=-1Kj0QSHjBtPxEJf){target="_blank"}
2. Pendrive/USB drive (8GB or larger)
3. One ISO file of any Linux distribution. [Kubuntu](https://kubuntu.org/getkubuntu/){target="_blank"}
4. Software to create a bootable USB drive. [Ventoy](https://www.ventoy.net/en/download.html){target="_blank"}

## Prepare the USB Drive
1. Insert your USB drive and run Ventoy
2. Format your USB drive with Ventoy to make it bootable
3. Just Copy and paste the Linux distribution ISO files into the USB drive
4. To be sure that iso file not got corrupted, you can run sha256sum and check both on local and server matches or not

## Prepare Your Laptop/Computer
- Restart your computer
- Go to BIOS/UEFI Settings
    - On HP laptops: restart and keep pressing the `F10` key
- Navigate to Boot Settings
- `Disable Secure Boot` (you can re-enable it after installation)

## Installation Process
Once your USB drive and laptop BIOS/UEFI settings are ready, proceed with the installation:

- Restart your computer
- Go to Boot Device Options
    - On HP laptops: keep pressing the `F9` key
- Choose your USB Drive
- If using Ventoy:
    - It will ask which OS to boot (based on the ISOs you've copied)
- If using BalenaEtcher: it will directly boot into that particular OS
- For Kubuntu installation:
    - Click on "Install"
    - Select language, keyboard layout, etc.
    - When choosing where to install or configure `partitions`:
        - Choose `Replace Partition` --> then Select the newly created(shrinked) 30GB partition
        - The installer will format two partitions
            - One for your Linux installation that you just selected
            - One will be EFI partition of windows(first partition in most cases)
    - Choose your username, password, etc., and proceed
    - Once installation is complete, your computer will automatically reboot or ask you to remove the USB drive and press Enter
    - Remove the USB drive and press Enter to reboot

## Final Computer Setup
- Restart your computer
- Go to BIOS/UEFI settings
    - You can enable Secure Boot if desired
- Most importantly:
    - Navigate to Boot Settings
    - Change the boot order
    - Set Ubuntu/Linux as the first boot option

## Final Notes
- When you turn on your computer, you'll have the option to boot into Ubuntu or Windows
- **Important**: 
    - The first time you boot into Windows after installation:
        - You may see a blue screen asking for a BitLocker recovery key
        - You can easily log in with your Microsoft account and retrieve the password from [BitLocker Recovery](https://account.microsoft.com/devices/recoverykey){target="_blank"}
        - This will only be asked once.

## Resources

- [BitLocker Recovery](https://account.microsoft.com/devices/recoverykey){target="_blank"}
- [Kubuntu ISO](https://kubuntu.org/getkubuntu/){target="_blank"}
- [Ventoy](https://www.ventoy.net/en/download.html){target="_blank"}

### Video Tutorials
- Shrink Partition {{< video https://www.youtube.com/embed/eJYwbqlAMd4 >}}
