<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>session2-networking-web – TDS by HRM</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-f1aadacce99040138bbb613f9330654f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c2cb7e0b3076a20157071e492cb50f0b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-0c5b58de5cf64f3542caacbc690827f7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-c2cb7e0b3076a20157071e492cb50f0b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed fullcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">TDS by HRM</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-wide tools-end">
    <a href="https://youtube.com/playlist?list=PLn_Nuy1c1Oj_Vc_UD8aCZOE_UoURk1S6F&amp;si=D1b0tRL25mGvlm2t" title="" class="quarto-navigation-tool px-1" aria-label="" target="_blank"><i class="bi bi-youtube"></i></a>
    <a href="https://hrmiitm.github.io" title="" class="quarto-navigation-tool px-1" aria-label="" target="_blank"><i class="bi bi-house"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"></h1>
        </a>     
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>About The Course</strong></span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Week-0 Foundation</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../W0/1_wsl_setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">WSL</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../W0/2_linux_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Installations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../W0/3_navigation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">File Navigation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../W0/4_shells.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Shell Config</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../W0/5_run.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Running Scripts</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text"><strong>Week-1 Linux Understanding</strong></span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../W1/1_program_path.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Program &amp; Path</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../W1/2_venv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Virtual Environment</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>





<section id="session-2-networking-and-the-web" class="level1">
<h1>Session 2: Networking and the Web</h1>
<p><strong>📅 Saturday, January 17 | 🕑 2:00 PM - 4:00 PM</strong></p>
<hr>
<section id="session-objectives" class="level2">
<h2 class="anchored" data-anchor-id="session-objectives">🎯 Session Objectives</h2>
<p>By the end of this session, students will: - Understand how computers communicate over networks - Know how VMs communicate with each other and the host - Understand the client-server model of the web - Be able to create a FastAPI server and expose it via Ngrok - Master HTTP requests using curl</p>
<hr>
</section>
</section>
<section id="part-1-networking-basics" class="level1">
<h1>Part 1: Networking Basics</h1>
<section id="how-computers-communicate" class="level2">
<h2 class="anchored" data-anchor-id="how-computers-communicate">How Computers Communicate</h2>
<section id="the-big-picture" class="level3">
<h3 class="anchored" data-anchor-id="the-big-picture">The Big Picture</h3>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                         THE INTERNET                                     │
│                                                                          │
│    🖥️ Your Computer                           🖥️ Server                 │
│    ┌──────────────┐                          ┌──────────────┐           │
│    │ IP: 192.168.x│    ════════════════►     │ IP: 93.184.x │           │
│    │              │    Request: GET /page    │              │           │
│    │              │    ◄════════════════     │              │           │
│    │              │    Response: HTML        │              │           │
│    └──────────────┘                          └──────────────┘           │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="what-is-an-ip-address" class="level3">
<h3 class="anchored" data-anchor-id="what-is-an-ip-address">What is an IP Address?</h3>
<p>An <strong>IP Address</strong> is like a postal address for computers.</p>
<pre><code>┌─────────────────────────────────────────────────────────────┐
│                    IP ADDRESS TYPES                          │
├─────────────────────────────────────────────────────────────┤
│                                                              │
│   IPv4: 192.168.1.100        (4 numbers, 0-255 each)        │
│         └─┬─┘ └┬┘ └┬┘ └─┬─┘                                 │
│         Network    │    Host                                 │
│                    │                                         │
│   IPv6: 2001:0db8:85a3:0000:0000:8a2e:0370:7334             │
│         (8 groups of 4 hex digits - newer, more addresses)  │
│                                                              │
├─────────────────────────────────────────────────────────────┤
│                    SPECIAL ADDRESSES                         │
├─────────────────────────────────────────────────────────────┤
│   127.0.0.1  = localhost (your own machine)                 │
│   0.0.0.0    = all interfaces (listen on everything)        │
│   192.168.x.x = private network (home/office)               │
│   10.x.x.x   = private network (larger organizations)       │
└─────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="try-it-yourself-find-your-ip-address" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-find-your-ip-address">🧪 Try It Yourself: Find Your IP Address</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># Open your terminal and run:</span></span>
<span id="cb3-2"><a href="#cb3-2"></a></span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="co"># On Linux/WSL/macOS:</span></span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="ex">ip</span> addr show</span>
<span id="cb3-5"><a href="#cb3-5"></a><span class="co"># or simply:</span></span>
<span id="cb3-6"><a href="#cb3-6"></a><span class="fu">hostname</span> <span class="at">-I</span></span>
<span id="cb3-7"><a href="#cb3-7"></a></span>
<span id="cb3-8"><a href="#cb3-8"></a><span class="co"># On Windows PowerShell:</span></span>
<span id="cb3-9"><a href="#cb3-9"></a><span class="ex">ipconfig</span></span>
<span id="cb3-10"><a href="#cb3-10"></a></span>
<span id="cb3-11"><a href="#cb3-11"></a><span class="co"># Try pinging localhost:</span></span>
<span id="cb3-12"><a href="#cb3-12"></a><span class="fu">ping</span> 127.0.0.1</span>
<span id="cb3-13"><a href="#cb3-13"></a><span class="co"># You're pinging yourself! Press Ctrl+C to stop.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Expected Output:</strong></p>
<pre><code>PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.031 ms</code></pre>
<blockquote class="blockquote">
<p>💡 <strong>Beginner Tip:</strong> <code>127.0.0.1</code> always means “this computer”. It never fails!</p>
</blockquote>
</section>
<section id="what-is-a-port" class="level3">
<h3 class="anchored" data-anchor-id="what-is-a-port">What is a Port?</h3>
<p>If IP is the <strong>building address</strong>, the Port is the <strong>apartment number</strong>.</p>
<pre><code>┌─────────────────────────────────────────────────────────────┐
│                     YOUR COMPUTER                            │
│  ┌────────────────────────────────────────────────────────┐ │
│  │                                                         │ │
│  │   IP Address: 192.168.1.100                            │ │
│  │                                                         │ │
│  │   ┌─────────┐ ┌─────────┐ ┌─────────┐ ┌─────────┐     │ │
│  │   │ Port 22 │ │ Port 80 │ │Port 443 │ │Port 8000│     │ │
│  │   │   SSH   │ │  HTTP   │ │  HTTPS  │ │ FastAPI │     │ │
│  │   └─────────┘ └─────────┘ └─────────┘ └─────────┘     │ │
│  │                                                         │ │
│  └────────────────────────────────────────────────────────┘ │
└─────────────────────────────────────────────────────────────┘</code></pre>
<p><strong>Common Ports:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Port</th>
<th>Service</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>22</td>
<td>SSH</td>
<td>Secure Shell (remote login)</td>
</tr>
<tr class="even">
<td>80</td>
<td>HTTP</td>
<td>Web traffic (unencrypted)</td>
</tr>
<tr class="odd">
<td>443</td>
<td>HTTPS</td>
<td>Web traffic (encrypted)</td>
</tr>
<tr class="even">
<td>3000</td>
<td>Dev Server</td>
<td>React, Node.js default</td>
</tr>
<tr class="odd">
<td>5000</td>
<td>Flask</td>
<td>Python Flask default</td>
</tr>
<tr class="even">
<td>8000</td>
<td>FastAPI</td>
<td>Python FastAPI default</td>
</tr>
<tr class="odd">
<td>5432</td>
<td>PostgreSQL</td>
<td>Database</td>
</tr>
<tr class="even">
<td>3306</td>
<td>MySQL</td>
<td>Database</td>
</tr>
</tbody>
</table>
</section>
<section id="try-it-yourself-check-whats-running-on-ports" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-check-whats-running-on-ports">🧪 Try It Yourself: Check What’s Running on Ports</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># See all ports in use on your machine:</span></span>
<span id="cb6-2"><a href="#cb6-2"></a></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="co"># Linux/WSL:</span></span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="ex">ss</span> <span class="at">-tulpn</span></span>
<span id="cb6-5"><a href="#cb6-5"></a></span>
<span id="cb6-6"><a href="#cb6-6"></a><span class="co"># Or the older way:</span></span>
<span id="cb6-7"><a href="#cb6-7"></a><span class="fu">netstat</span> <span class="at">-tulpn</span></span>
<span id="cb6-8"><a href="#cb6-8"></a></span>
<span id="cb6-9"><a href="#cb6-9"></a><span class="co"># macOS:</span></span>
<span id="cb6-10"><a href="#cb6-10"></a><span class="ex">lsof</span> <span class="at">-i</span> <span class="at">-P</span> <span class="kw">|</span> <span class="fu">head</span> <span class="at">-20</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Example Output:</strong></p>
<pre><code>Proto  Local Address    State    PID/Program
tcp    0.0.0.0:22       LISTEN   sshd
tcp    127.0.0.1:5432   LISTEN   postgres</code></pre>
<blockquote class="blockquote">
<p>💡 <strong>Reading this:</strong> “PostgreSQL is listening on port 5432, but only for local connections (127.0.0.1)”</p>
</blockquote>
</section>
<section id="the-osi-model-simplified" class="level3">
<h3 class="anchored" data-anchor-id="the-osi-model-simplified">The OSI Model (Simplified)</h3>
<pre><code>┌─────────────────────────────────────────────────────────────┐
│                    OSI MODEL (7 LAYERS)                      │
├─────────────────────────────────────────────────────────────┤
│                                                              │
│   Layer 7: APPLICATION    ← HTTP, HTTPS, FTP, SSH           │
│              ↓                (What you interact with)       │
│   Layer 6: PRESENTATION   ← Encryption, Compression         │
│              ↓                                               │
│   Layer 5: SESSION        ← Managing connections            │
│              ↓                                               │
│   Layer 4: TRANSPORT      ← TCP, UDP (Port numbers here)    │
│              ↓                                               │
│   Layer 3: NETWORK        ← IP Addresses, Routing           │
│              ↓                                               │
│   Layer 2: DATA LINK      ← MAC Addresses, Switches         │
│              ↓                                               │
│   Layer 1: PHYSICAL       ← Cables, WiFi, Signals           │
│                                                              │
└─────────────────────────────────────────────────────────────┘

    ┌──────────────────────────────────────────────────────┐
    │  SIMPLIFIED VERSION (TCP/IP - 4 Layers)              │
    ├──────────────────────────────────────────────────────┤
    │  APPLICATION  ← HTTP, DNS, FTP                       │
    │  TRANSPORT    ← TCP, UDP                             │
    │  INTERNET     ← IP                                   │
    │  NETWORK      ← Ethernet, WiFi                       │
    └──────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="tcp-vs-udp" class="level3">
<h3 class="anchored" data-anchor-id="tcp-vs-udp">TCP vs UDP</h3>
<pre><code>┌──────────────────────────────────────────────────────────────────────┐
│                        TCP vs UDP                                     │
├─────────────────────────────────┬────────────────────────────────────┤
│              TCP                │              UDP                    │
├─────────────────────────────────┼────────────────────────────────────┤
│                                 │                                     │
│   📞 Like a Phone Call          │   📮 Like Sending Postcards         │
│                                 │                                     │
│   ✓ Connection established      │   ✗ No connection needed           │
│   ✓ Guaranteed delivery         │   ✗ No guarantee                   │
│   ✓ Ordered packets             │   ✗ May arrive out of order        │
│   ✓ Error checking              │   ✗ No error checking              │
│   ✗ Slower                      │   ✓ Faster                         │
│                                 │                                     │
│   Use for: Web, Email, Files    │   Use for: Gaming, Video, DNS     │
│                                 │                                     │
└─────────────────────────────────┴────────────────────────────────────┘</code></pre>
</section>
<section id="dns-the-internets-phone-book" class="level3">
<h3 class="anchored" data-anchor-id="dns-the-internets-phone-book">DNS: The Internet’s Phone Book</h3>
<pre><code>┌─────────────────────────────────────────────────────────────────────┐
│                     DNS RESOLUTION                                   │
├─────────────────────────────────────────────────────────────────────┤
│                                                                      │
│   You type: www.google.com                                          │
│                                                                      │
│   ┌─────────┐    "What's google.com?"    ┌─────────────┐           │
│   │ Browser │ ─────────────────────────► │ DNS Server  │           │
│   │         │ ◄───────────────────────── │             │           │
│   └─────────┘    "It's 142.250.190.46"   └─────────────┘           │
│        │                                                             │
│        │         Now browser connects to 142.250.190.46             │
│        ▼                                                             │
│   ┌─────────────────────────────────────────┐                       │
│   │         Google's Server                  │                       │
│   │         IP: 142.250.190.46              │                       │
│   └─────────────────────────────────────────┘                       │
│                                                                      │
└─────────────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="try-it-yourself-dns-lookup" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-dns-lookup">🧪 Try It Yourself: DNS Lookup</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1"></a><span class="co"># Find the IP address of any website:</span></span>
<span id="cb11-2"><a href="#cb11-2"></a></span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="ex">nslookup</span> google.com</span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="co"># Output: Address: 142.250.190.46</span></span>
<span id="cb11-5"><a href="#cb11-5"></a></span>
<span id="cb11-6"><a href="#cb11-6"></a><span class="co"># Or use dig (more detailed):</span></span>
<span id="cb11-7"><a href="#cb11-7"></a><span class="ex">dig</span> google.com +short</span>
<span id="cb11-8"><a href="#cb11-8"></a><span class="co"># Output: 142.250.190.46</span></span>
<span id="cb11-9"><a href="#cb11-9"></a></span>
<span id="cb11-10"><a href="#cb11-10"></a><span class="co"># Try with different websites:</span></span>
<span id="cb11-11"><a href="#cb11-11"></a><span class="ex">nslookup</span> github.com</span>
<span id="cb11-12"><a href="#cb11-12"></a><span class="ex">nslookup</span> iitm.ac.in</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Real Example:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1"></a><span class="ex">$</span> nslookup github.com</span>
<span id="cb12-2"><a href="#cb12-2"></a><span class="ex">Server:</span>    127.0.0.53</span>
<span id="cb12-3"><a href="#cb12-3"></a><span class="ex">Address:</span>   127.0.0.53#53</span>
<span id="cb12-4"><a href="#cb12-4"></a></span>
<span id="cb12-5"><a href="#cb12-5"></a><span class="ex">Non-authoritative</span> answer:</span>
<span id="cb12-6"><a href="#cb12-6"></a><span class="ex">Name:</span>   github.com</span>
<span id="cb12-7"><a href="#cb12-7"></a><span class="ex">Address:</span> 20.207.73.82</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<blockquote class="blockquote">
<p>💡 <strong>What just happened?</strong> Your computer asked a DNS server “What’s github.com’s IP?” and got <code>20.207.73.82</code> back!</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="part-2-how-vms-communicate-over-networks" class="level1">
<h1>Part 2: How VMs Communicate Over Networks</h1>
<section id="network-modes-in-virtual-machines" class="level2">
<h2 class="anchored" data-anchor-id="network-modes-in-virtual-machines">Network Modes in Virtual Machines</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                    VM NETWORKING MODES                                   │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   1. NAT (Network Address Translation) - DEFAULT                        │
│   ┌────────────────────────────────────────────────────────────────┐   │
│   │  HOST (192.168.1.100)                                           │   │
│   │  ┌──────────────────┐                                           │   │
│   │  │  VM              │                                           │   │
│   │  │  IP: 10.0.2.15   │───► NAT ───► Internet                    │   │
│   │  │  (Private)       │     (Host's IP used)                      │   │
│   │  └──────────────────┘                                           │   │
│   └────────────────────────────────────────────────────────────────┘   │
│   ✓ VM can access internet    ✗ Can't access VM from outside          │
│                                                                          │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   2. BRIDGED - VM gets its own IP on your network                       │
│   ┌────────────────────────────────────────────────────────────────┐   │
│   │                      ROUTER (192.168.1.1)                       │   │
│   │                           │                                      │   │
│   │          ┌────────────────┼────────────────┐                    │   │
│   │          │                │                │                    │   │
│   │     ┌────▼────┐      ┌────▼────┐     ┌────▼────┐               │   │
│   │     │  HOST   │      │   VM    │     │ Other   │               │   │
│   │     │.1.100   │      │ .1.150  │     │ .1.101  │               │   │
│   │     └─────────┘      └─────────┘     └─────────┘               │   │
│   └────────────────────────────────────────────────────────────────┘   │
│   ✓ VM appears as separate device    ✓ Others can access VM           │
│                                                                          │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   3. HOST-ONLY - VM can only talk to Host                               │
│   ┌────────────────────────────────────────────────────────────────┐   │
│   │                                                                  │   │
│   │     ┌─────────┐         ┌─────────┐                             │   │
│   │     │  HOST   │◄───────►│   VM    │         ╳ No Internet      │   │
│   │     │         │         │         │                             │   │
│   │     └─────────┘         └─────────┘                             │   │
│   │                                                                  │   │
│   └────────────────────────────────────────────────────────────────┘   │
│   ✓ Isolated &amp; secure    ✗ No external network access                  │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="wsl2-networking" class="level2">
<h2 class="anchored" data-anchor-id="wsl2-networking">WSL2 Networking</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                    WSL2 NETWORK ARCHITECTURE                             │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   WINDOWS HOST                                                           │
│   ┌────────────────────────────────────────────────────────────────┐   │
│   │                                                                  │   │
│   │   Windows IP: 192.168.1.100  ◄──────────────► Internet         │   │
│   │         │                                                        │   │
│   │         │  Virtual Switch (NAT)                                  │   │
│   │         │                                                        │   │
│   │         ▼                                                        │   │
│   │   ┌──────────────────────────────────────────┐                  │   │
│   │   │            WSL2 VM                        │                  │   │
│   │   │                                           │                  │   │
│   │   │   eth0: 172.x.x.x (internal)             │                  │   │
│   │   │                                           │                  │   │
│   │   │   localhost:8000  ──► Windows localhost  │                  │   │
│   │   │                       (automatic forward) │                  │   │
│   │   └──────────────────────────────────────────┘                  │   │
│   │                                                                  │   │
│   └────────────────────────────────────────────────────────────────┘   │
│                                                                          │
│   KEY POINTS:                                                            │
│   • WSL2 gets its own IP (172.x.x.x range)                              │
│   • localhost is shared between Windows and WSL                         │
│   • Services on WSL can be accessed from Windows via localhost          │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<section id="useful-commands" class="level3">
<h3 class="anchored" data-anchor-id="useful-commands">Useful Commands</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># Check your IP address</span></span>
<span id="cb15-2"><a href="#cb15-2"></a><span class="ex">ip</span> addr show          <span class="co"># Linux/WSL</span></span>
<span id="cb15-3"><a href="#cb15-3"></a><span class="ex">ipconfig</span>              <span class="co"># Windows (in PowerShell)</span></span>
<span id="cb15-4"><a href="#cb15-4"></a></span>
<span id="cb15-5"><a href="#cb15-5"></a><span class="co"># Check WSL IP specifically</span></span>
<span id="cb15-6"><a href="#cb15-6"></a><span class="fu">hostname</span> <span class="at">-I</span>           <span class="co"># In WSL</span></span>
<span id="cb15-7"><a href="#cb15-7"></a></span>
<span id="cb15-8"><a href="#cb15-8"></a><span class="co"># Check what ports are in use</span></span>
<span id="cb15-9"><a href="#cb15-9"></a><span class="fu">netstat</span> <span class="at">-tulpn</span>        <span class="co"># Linux</span></span>
<span id="cb15-10"><a href="#cb15-10"></a><span class="fu">netstat</span> <span class="at">-an</span>           <span class="co"># Windows</span></span>
<span id="cb15-11"><a href="#cb15-11"></a></span>
<span id="cb15-12"><a href="#cb15-12"></a><span class="co"># Test connectivity</span></span>
<span id="cb15-13"><a href="#cb15-13"></a><span class="fu">ping</span> google.com</span>
<span id="cb15-14"><a href="#cb15-14"></a><span class="fu">ping</span> 192.168.1.1      <span class="co"># Your router</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="try-it-yourself-test-network-connectivity" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-test-network-connectivity">🧪 Try It Yourself: Test Network Connectivity</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># Step 1: Can you reach the internet?</span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="fu">ping</span> <span class="at">-c</span> 4 google.com</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="co"># If this works, your internet is fine!</span></span>
<span id="cb16-4"><a href="#cb16-4"></a></span>
<span id="cb16-5"><a href="#cb16-5"></a><span class="co"># Step 2: Check your WSL/Linux IP</span></span>
<span id="cb16-6"><a href="#cb16-6"></a><span class="fu">hostname</span> <span class="at">-I</span></span>
<span id="cb16-7"><a href="#cb16-7"></a><span class="co"># Example output: 172.25.160.1</span></span>
<span id="cb16-8"><a href="#cb16-8"></a></span>
<span id="cb16-9"><a href="#cb16-9"></a><span class="co"># Step 3: From Windows, can you ping WSL?</span></span>
<span id="cb16-10"><a href="#cb16-10"></a><span class="co"># Open PowerShell and run:</span></span>
<span id="cb16-11"><a href="#cb16-11"></a><span class="fu">ping</span> 172.25.160.1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>What Success Looks Like:</strong></p>
<pre><code>PING google.com (142.250.190.46) 56(84) bytes of data.
64 bytes from 142.250.190.46: icmp_seq=1 ttl=117 time=15.2 ms
64 bytes from 142.250.190.46: icmp_seq=2 ttl=117 time=14.8 ms

--- google.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss</code></pre>
<blockquote class="blockquote">
<p>💡 <strong>If ping fails:</strong> Check if you’re connected to WiFi, or try <code>ping 8.8.8.8</code> (Google’s DNS server)</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="part-3-how-the-web-works-clientserver" class="level1">
<h1>Part 3: How the Web Works (Client/Server)</h1>
<section id="the-client-server-model" class="level2">
<h2 class="anchored" data-anchor-id="the-client-server-model">The Client-Server Model</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                    CLIENT-SERVER MODEL                                   │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│      CLIENT                                         SERVER               │
│   (Your Browser)                               (Web Server)              │
│                                                                          │
│   ┌─────────────┐                              ┌─────────────┐          │
│   │             │     1. REQUEST               │             │          │
│   │   🌐        │  ─────────────────────────►  │    🖥️       │          │
│   │   Browser   │     GET /index.html          │   Server    │          │
│   │             │                              │             │          │
│   │             │     2. RESPONSE              │             │          │
│   │             │  ◄─────────────────────────  │             │          │
│   │             │     HTML, CSS, JS            │             │          │
│   └─────────────┘                              └─────────────┘          │
│                                                                          │
│   CLIENT:                          SERVER:                               │
│   • Initiates requests             • Waits for requests                 │
│   • Renders content                • Processes requests                 │
│   • User interaction               • Sends responses                    │
│   • Browser, Mobile App            • Runs 24/7                          │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="anatomy-of-a-url" class="level2">
<h2 class="anchored" data-anchor-id="anatomy-of-a-url">Anatomy of a URL</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                        URL BREAKDOWN                                     │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   https://api.example.com:8080/users/123?active=true#section1           │
│   └─┬──┘ └───────┬───────┘└─┬─┘└────┬───┘└────┬────┘└───┬────┘          │
│     │            │          │       │         │         │                │
│   Protocol    Domain      Port    Path      Query    Fragment           │
│                                              Params                      │
│                                                                          │
│   ┌────────────────────────────────────────────────────────────────┐   │
│   │  PROTOCOL    │  https = secure, http = not secure              │   │
│   │  DOMAIN      │  The server's address (resolved via DNS)        │   │
│   │  PORT        │  Optional; defaults: 80 (http), 443 (https)     │   │
│   │  PATH        │  Resource location on server                    │   │
│   │  QUERY       │  Key-value parameters (?key=value&amp;key2=val2)    │   │
│   │  FRAGMENT    │  Client-side anchor (not sent to server)        │   │
│   └────────────────────────────────────────────────────────────────┘   │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<section id="try-it-yourself-break-down-a-url" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-break-down-a-url">🧪 Try It Yourself: Break Down a URL</h3>
<p>Look at this URL and identify each part:</p>
<pre><code>https://www.amazon.in:443/s?k=laptop&amp;ref=nav_logo</code></pre>
<p><strong>Answer:</strong> | Part | Value | |——|——-| | Protocol | <code>https</code> | | Domain | <code>www.amazon.in</code> | | Port | <code>443</code> (default for HTTPS) | | Path | <code>/s</code> | | Query Params | <code>k=laptop</code> and <code>ref=nav_logo</code> |</p>
<blockquote class="blockquote">
<p>💡 <strong>Try this:</strong> Open your browser’s address bar and break down any URL you visit!</p>
</blockquote>
</section>
</section>
<section id="http-requestresponse-cycle" class="level2">
<h2 class="anchored" data-anchor-id="http-requestresponse-cycle">HTTP Request/Response Cycle</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                    HTTP REQUEST/RESPONSE                                 │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   ══════════════════════ REQUEST ══════════════════════                 │
│                                                                          │
│   ┌────────────────────────────────────────────────────────────────┐   │
│   │  GET /api/users HTTP/1.1           ← Method + Path + Version   │   │
│   │  Host: api.example.com             ← Required Header           │   │
│   │  Authorization: Bearer token123    ← Auth Header               │   │
│   │  Content-Type: application/json    ← Body type                 │   │
│   │  Accept: application/json          ← Expected response type    │   │
│   │                                                                 │   │
│   │  {"name": "John", "email": "..."}  ← Body (for POST/PUT)       │   │
│   └────────────────────────────────────────────────────────────────┘   │
│                                                                          │
│   ═══════════════════════ RESPONSE ═════════════════════════            │
│                                                                          │
│   ┌────────────────────────────────────────────────────────────────┐   │
│   │  HTTP/1.1 200 OK                   ← Status Line               │   │
│   │  Content-Type: application/json    ← Response type             │   │
│   │  Content-Length: 234               ← Body size                 │   │
│   │  Cache-Control: no-cache           ← Caching rules             │   │
│   │                                                                 │   │
│   │  {"users": [...]}                  ← Response Body             │   │
│   └────────────────────────────────────────────────────────────────┘   │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="http-methods" class="level2">
<h2 class="anchored" data-anchor-id="http-methods">HTTP Methods</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                        HTTP METHODS                                      │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   METHOD     CRUD        DESCRIPTION            EXAMPLE                  │
│   ────────────────────────────────────────────────────────────────      │
│                                                                          │
│   GET        READ        Retrieve data          GET /users               │
│                          (No body)              GET /users/123           │
│                                                                          │
│   POST       CREATE      Create new resource    POST /users              │
│                          (Has body)             Body: {"name": "John"}   │
│                                                                          │
│   PUT        UPDATE      Replace resource       PUT /users/123           │
│                          (Has body)             Body: {"name": "Jane"}   │
│                                                                          │
│   PATCH      UPDATE      Partial update         PATCH /users/123         │
│                          (Has body)             Body: {"name": "Jane"}   │
│                                                                          │
│   DELETE     DELETE      Remove resource        DELETE /users/123        │
│                          (Usually no body)                               │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="http-status-codes" class="level2">
<h2 class="anchored" data-anchor-id="http-status-codes">HTTP Status Codes</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                     HTTP STATUS CODES                                    │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   1xx  INFORMATIONAL  ────────────────────────────────────────────      │
│        100 Continue                                                      │
│                                                                          │
│   2xx  SUCCESS ✅     ────────────────────────────────────────────      │
│        200 OK                    Request succeeded                       │
│        201 Created               Resource created (POST)                 │
│        204 No Content            Success but no body                     │
│                                                                          │
│   3xx  REDIRECTION 🔄 ────────────────────────────────────────────      │
│        301 Moved Permanently     URL changed forever                     │
│        302 Found                 Temporary redirect                      │
│        304 Not Modified          Use cached version                      │
│                                                                          │
│   4xx  CLIENT ERROR ❌ ───────────────────────────────────────────      │
│        400 Bad Request           Invalid syntax                          │
│        401 Unauthorized          Auth required                           │
│        403 Forbidden             No permission                           │
│        404 Not Found             Resource doesn't exist                  │
│        422 Unprocessable         Validation failed                       │
│        429 Too Many Requests     Rate limited                            │
│                                                                          │
│   5xx  SERVER ERROR 💥 ───────────────────────────────────────────      │
│        500 Internal Error        Server crashed                          │
│        502 Bad Gateway           Upstream server error                   │
│        503 Service Unavailable   Server overloaded                       │
│        504 Gateway Timeout       Upstream timeout                        │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<section id="try-it-yourself-see-different-status-codes" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-see-different-status-codes">🧪 Try It Yourself: See Different Status Codes</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb24-1"><a href="#cb24-1"></a><span class="co"># See a 200 OK response:</span></span>
<span id="cb24-2"><a href="#cb24-2"></a><span class="ex">curl</span> <span class="at">-I</span> https://www.google.com</span>
<span id="cb24-3"><a href="#cb24-3"></a><span class="co"># HTTP/2 200 ✅</span></span>
<span id="cb24-4"><a href="#cb24-4"></a></span>
<span id="cb24-5"><a href="#cb24-5"></a><span class="co"># See a 404 Not Found:</span></span>
<span id="cb24-6"><a href="#cb24-6"></a><span class="ex">curl</span> <span class="at">-I</span> https://github.com/this-page-does-not-exist-12345</span>
<span id="cb24-7"><a href="#cb24-7"></a><span class="co"># HTTP/2 404 ❌</span></span>
<span id="cb24-8"><a href="#cb24-8"></a></span>
<span id="cb24-9"><a href="#cb24-9"></a><span class="co"># See a 301 Redirect:</span></span>
<span id="cb24-10"><a href="#cb24-10"></a><span class="ex">curl</span> <span class="at">-I</span> http://github.com</span>
<span id="cb24-11"><a href="#cb24-11"></a><span class="co"># HTTP/1.1 301 Moved Permanently</span></span>
<span id="cb24-12"><a href="#cb24-12"></a><span class="co"># Location: https://github.com/</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<blockquote class="blockquote">
<p>💡 <strong>The <code>-I</code> flag</strong> shows only headers, not the full page content!</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="part-4-fastapi-server-ngrok-tunnel" class="level1">
<h1>Part 4: FastAPI Server + Ngrok Tunnel</h1>
<section id="what-is-fastapi" class="level2">
<h2 class="anchored" data-anchor-id="what-is-fastapi">What is FastAPI?</h2>
<p>FastAPI is a modern Python web framework for building APIs.</p>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                       WHY FASTAPI?                                       │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   ⚡ FAST         - One of the fastest Python frameworks                │
│   📝 EASY         - Minimal code to get started                         │
│   📚 AUTO DOCS    - Swagger UI generated automatically                  │
│   ✅ VALIDATION   - Automatic request/response validation               │
│   🔄 ASYNC        - Supports async/await for concurrency                │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="step-1-create-a-fastapi-server" class="level2">
<h2 class="anchored" data-anchor-id="step-1-create-a-fastapi-server">Step 1: Create a FastAPI Server</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb26-1"><a href="#cb26-1"></a><span class="co"># Install FastAPI and Uvicorn</span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="ex">pip</span> install fastapi uvicorn</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Create <code>main.py</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1"></a><span class="im">from</span> fastapi <span class="im">import</span> FastAPI</span>
<span id="cb27-2"><a href="#cb27-2"></a></span>
<span id="cb27-3"><a href="#cb27-3"></a><span class="co"># Create the app</span></span>
<span id="cb27-4"><a href="#cb27-4"></a>app <span class="op">=</span> FastAPI(title<span class="op">=</span><span class="st">"My First API"</span>)</span>
<span id="cb27-5"><a href="#cb27-5"></a></span>
<span id="cb27-6"><a href="#cb27-6"></a><span class="co"># Root endpoint</span></span>
<span id="cb27-7"><a href="#cb27-7"></a><span class="at">@app.get</span>(<span class="st">"/"</span>)</span>
<span id="cb27-8"><a href="#cb27-8"></a><span class="kw">def</span> read_root():</span>
<span id="cb27-9"><a href="#cb27-9"></a>    <span class="cf">return</span> {<span class="st">"message"</span>: <span class="st">"Hello, TDS Students! 👋"</span>}</span>
<span id="cb27-10"><a href="#cb27-10"></a></span>
<span id="cb27-11"><a href="#cb27-11"></a><span class="co"># Get item by ID</span></span>
<span id="cb27-12"><a href="#cb27-12"></a><span class="at">@app.get</span>(<span class="st">"/items/</span><span class="sc">{item_id}</span><span class="st">"</span>)</span>
<span id="cb27-13"><a href="#cb27-13"></a><span class="kw">def</span> read_item(item_id: <span class="bu">int</span>, q: <span class="bu">str</span> <span class="op">=</span> <span class="va">None</span>):</span>
<span id="cb27-14"><a href="#cb27-14"></a>    <span class="cf">return</span> {</span>
<span id="cb27-15"><a href="#cb27-15"></a>        <span class="st">"item_id"</span>: item_id, </span>
<span id="cb27-16"><a href="#cb27-16"></a>        <span class="st">"query"</span>: q</span>
<span id="cb27-17"><a href="#cb27-17"></a>    }</span>
<span id="cb27-18"><a href="#cb27-18"></a></span>
<span id="cb27-19"><a href="#cb27-19"></a><span class="co"># POST example</span></span>
<span id="cb27-20"><a href="#cb27-20"></a><span class="at">@app.post</span>(<span class="st">"/items"</span>)</span>
<span id="cb27-21"><a href="#cb27-21"></a><span class="kw">def</span> create_item(name: <span class="bu">str</span>, price: <span class="bu">float</span>):</span>
<span id="cb27-22"><a href="#cb27-22"></a>    <span class="cf">return</span> {</span>
<span id="cb27-23"><a href="#cb27-23"></a>        <span class="st">"name"</span>: name,</span>
<span id="cb27-24"><a href="#cb27-24"></a>        <span class="st">"price"</span>: price,</span>
<span id="cb27-25"><a href="#cb27-25"></a>        <span class="st">"status"</span>: <span class="st">"created"</span></span>
<span id="cb27-26"><a href="#cb27-26"></a>    }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Run the server:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb28-1"><a href="#cb28-1"></a><span class="ex">uvicorn</span> main:app <span class="at">--reload</span> <span class="at">--host</span> 0.0.0.0 <span class="at">--port</span> 8000</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                    YOUR SERVER IS NOW RUNNING                            │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   LOCAL ACCESS:                                                          │
│   • http://localhost:8000           - Your API                          │
│   • http://localhost:8000/docs      - Swagger UI (Interactive docs)     │
│   • http://localhost:8000/redoc     - ReDoc (Alternative docs)          │
│                                                                          │
│   PROBLEM: Only accessible from YOUR computer!                          │
│   SOLUTION: Ngrok creates a public tunnel                               │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<section id="try-it-yourself-your-first-api" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-your-first-api">🧪 Try It Yourself: Your First API!</h3>
<p><strong>Step 1:</strong> Create a file called <code>main.py</code> with the code above</p>
<p><strong>Step 2:</strong> Run the server:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb30-1"><a href="#cb30-1"></a><span class="ex">uvicorn</span> main:app <span class="at">--reload</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Step 3:</strong> Test in your browser: - Open http://localhost:8000 → You’ll see: <code>{"message":"Hello, TDS Students! 👋"}</code> - Open http://localhost:8000/items/42?q=hello → You’ll see: <code>{"item_id":42,"query":"hello"}</code> - Open http://localhost:8000/docs → Interactive API playground! 🎮</p>
<p><strong>Step 4:</strong> Test with curl:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb31-1"><a href="#cb31-1"></a><span class="ex">curl</span> http://localhost:8000/</span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="co"># {"message":"Hello, TDS Students! 👋"}</span></span>
<span id="cb31-3"><a href="#cb31-3"></a></span>
<span id="cb31-4"><a href="#cb31-4"></a><span class="ex">curl</span> <span class="st">"http://localhost:8000/items/5?q=test"</span></span>
<span id="cb31-5"><a href="#cb31-5"></a><span class="co"># {"item_id":5,"query":"test"}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<blockquote class="blockquote">
<p>💡 <strong>Bonus:</strong> The <code>/docs</code> page lets you test your API without writing any code!</p>
</blockquote>
</section>
</section>
<section id="what-is-ngrok" class="level2">
<h2 class="anchored" data-anchor-id="what-is-ngrok">What is Ngrok?</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                      NGROK EXPLAINED                                     │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   WITHOUT NGROK:                                                         │
│                                                                          │
│   🌍 Internet User                     🖥️ Your Computer                 │
│        │                                    │                            │
│        │    "Cannot connect!"              │ localhost:8000             │
│        ╳─────────────────────────────────►│                             │
│        │    (No public IP/firewall)        │                            │
│                                                                          │
│   ─────────────────────────────────────────────────────────────────     │
│                                                                          │
│   WITH NGROK:                                                            │
│                                                                          │
│   🌍 Internet User      ☁️ Ngrok Cloud      🖥️ Your Computer            │
│        │                      │                   │                      │
│        │  https://abc123.     │                   │                      │
│        │    ngrok.io          │                   │                      │
│        │──────────────────►   │   Tunnel          │                      │
│        │                      │ ─────────────────►│ localhost:8000       │
│        │   ◄──────────────────│ ◄─────────────────│                      │
│        │     Response         │                   │                      │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="step-2-set-up-ngrok" class="level2">
<h2 class="anchored" data-anchor-id="step-2-set-up-ngrok">Step 2: Set Up Ngrok</h2>
<section id="install-ngrok" class="level3">
<h3 class="anchored" data-anchor-id="install-ngrok">Install Ngrok</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># Ubuntu/WSL</span></span>
<span id="cb33-2"><a href="#cb33-2"></a><span class="fu">sudo</span> snap install ngrok</span>
<span id="cb33-3"><a href="#cb33-3"></a></span>
<span id="cb33-4"><a href="#cb33-4"></a><span class="co"># OR download from ngrok.com and add to PATH</span></span>
<span id="cb33-5"><a href="#cb33-5"></a></span>
<span id="cb33-6"><a href="#cb33-6"></a><span class="co"># macOS</span></span>
<span id="cb33-7"><a href="#cb33-7"></a><span class="ex">brew</span> install ngrok</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="create-a-free-account" class="level3">
<h3 class="anchored" data-anchor-id="create-a-free-account">Create a Free Account</h3>
<ol type="1">
<li>Go to https://ngrok.com</li>
<li>Sign up for free</li>
<li>Get your auth token from dashboard</li>
</ol>
</section>
<section id="configure-ngrok" class="level3">
<h3 class="anchored" data-anchor-id="configure-ngrok">Configure Ngrok</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb34-1"><a href="#cb34-1"></a><span class="ex">ngrok</span> config add-authtoken YOUR_AUTH_TOKEN_HERE</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="start-the-tunnel" class="level3">
<h3 class="anchored" data-anchor-id="start-the-tunnel">Start the Tunnel</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb35-1"><a href="#cb35-1"></a><span class="co"># In a NEW terminal (keep FastAPI running)</span></span>
<span id="cb35-2"><a href="#cb35-2"></a><span class="ex">ngrok</span> http 8000</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Output:</p>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                    NGROK OUTPUT                                          │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   Session Status    online                                               │
│   Account           your-email@example.com (Plan: Free)                  │
│   Version           3.x.x                                                │
│   Region            India (in)                                           │
│   Latency           45ms                                                 │
│                                                                          │
│   Forwarding        https://a1b2c3d4.ngrok-free.app -&gt; localhost:8000   │
│                     ↑                                                    │
│                     This is your PUBLIC URL!                             │
│                                                                          │
│   Connections       ttl     opn     rt1     rt5     p50     p90         │
│                     0       0       0.00    0.00    0.00    0.00        │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<p>Now <strong>anyone</strong> can access: - <code>https://a1b2c3d4.ngrok-free.app</code> - Your API - <code>https://a1b2c3d4.ngrok-free.app/docs</code> - Swagger docs</p>
<hr>
</section>
</section>
</section>
<section id="part-5-http-requests-with-curl" class="level1">
<h1>Part 5: HTTP Requests with curl</h1>
<section id="what-is-curl" class="level2">
<h2 class="anchored" data-anchor-id="what-is-curl">What is curl?</h2>
<p><strong>curl</strong> (Client URL) is a command-line tool for making HTTP requests.</p>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                        CURL BASICS                                       │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   curl [options] [URL]                                                  │
│                                                                          │
│   Common Options:                                                        │
│   -X, --request    HTTP method (GET, POST, PUT, DELETE)                 │
│   -H, --header     Add header                                           │
│   -d, --data       Request body                                         │
│   -o, --output     Save to file                                         │
│   -i, --include    Show response headers                                │
│   -v, --verbose    Debug mode (show everything)                         │
│   -s, --silent     No progress bar                                      │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
</section>
<section id="get-requests" class="level2">
<h2 class="anchored" data-anchor-id="get-requests">GET Requests</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb38-1"><a href="#cb38-1"></a><span class="co"># Simple GET request</span></span>
<span id="cb38-2"><a href="#cb38-2"></a><span class="ex">curl</span> http://localhost:8000/</span>
<span id="cb38-3"><a href="#cb38-3"></a></span>
<span id="cb38-4"><a href="#cb38-4"></a><span class="co"># GET with query parameters</span></span>
<span id="cb38-5"><a href="#cb38-5"></a><span class="ex">curl</span> <span class="st">"http://localhost:8000/items/42?q=search"</span></span>
<span id="cb38-6"><a href="#cb38-6"></a></span>
<span id="cb38-7"><a href="#cb38-7"></a><span class="co"># GET with headers</span></span>
<span id="cb38-8"><a href="#cb38-8"></a><span class="ex">curl</span> <span class="at">-H</span> <span class="st">"Accept: application/json"</span> http://localhost:8000/</span>
<span id="cb38-9"><a href="#cb38-9"></a></span>
<span id="cb38-10"><a href="#cb38-10"></a><span class="co"># Show response headers</span></span>
<span id="cb38-11"><a href="#cb38-11"></a><span class="ex">curl</span> <span class="at">-i</span> http://localhost:8000/</span>
<span id="cb38-12"><a href="#cb38-12"></a></span>
<span id="cb38-13"><a href="#cb38-13"></a><span class="co"># Verbose (debug) mode</span></span>
<span id="cb38-14"><a href="#cb38-14"></a><span class="ex">curl</span> <span class="at">-v</span> http://localhost:8000/</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="post-requests" class="level2">
<h2 class="anchored" data-anchor-id="post-requests">POST Requests</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb39-1"><a href="#cb39-1"></a><span class="co"># POST with JSON body</span></span>
<span id="cb39-2"><a href="#cb39-2"></a><span class="ex">curl</span> <span class="at">-X</span> POST http://localhost:8000/items <span class="dt">\</span></span>
<span id="cb39-3"><a href="#cb39-3"></a>  <span class="at">-H</span> <span class="st">"Content-Type: application/json"</span> <span class="dt">\</span></span>
<span id="cb39-4"><a href="#cb39-4"></a>  <span class="at">-d</span> <span class="st">'{"name": "Widget", "price": 29.99}'</span></span>
<span id="cb39-5"><a href="#cb39-5"></a></span>
<span id="cb39-6"><a href="#cb39-6"></a><span class="co"># POST with form data</span></span>
<span id="cb39-7"><a href="#cb39-7"></a><span class="ex">curl</span> <span class="at">-X</span> POST http://localhost:8000/login <span class="dt">\</span></span>
<span id="cb39-8"><a href="#cb39-8"></a>  <span class="at">-d</span> <span class="st">"username=john&amp;password=secret"</span></span>
<span id="cb39-9"><a href="#cb39-9"></a></span>
<span id="cb39-10"><a href="#cb39-10"></a><span class="co"># POST from file</span></span>
<span id="cb39-11"><a href="#cb39-11"></a><span class="ex">curl</span> <span class="at">-X</span> POST http://localhost:8000/items <span class="dt">\</span></span>
<span id="cb39-12"><a href="#cb39-12"></a>  <span class="at">-H</span> <span class="st">"Content-Type: application/json"</span> <span class="dt">\</span></span>
<span id="cb39-13"><a href="#cb39-13"></a>  <span class="at">-d</span> @data.json</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="put-and-delete" class="level2">
<h2 class="anchored" data-anchor-id="put-and-delete">PUT and DELETE</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb40-1"><a href="#cb40-1"></a><span class="co"># PUT (update)</span></span>
<span id="cb40-2"><a href="#cb40-2"></a><span class="ex">curl</span> <span class="at">-X</span> PUT http://localhost:8000/items/123 <span class="dt">\</span></span>
<span id="cb40-3"><a href="#cb40-3"></a>  <span class="at">-H</span> <span class="st">"Content-Type: application/json"</span> <span class="dt">\</span></span>
<span id="cb40-4"><a href="#cb40-4"></a>  <span class="at">-d</span> <span class="st">'{"name": "New Name", "price": 39.99}'</span></span>
<span id="cb40-5"><a href="#cb40-5"></a></span>
<span id="cb40-6"><a href="#cb40-6"></a><span class="co"># DELETE</span></span>
<span id="cb40-7"><a href="#cb40-7"></a><span class="ex">curl</span> <span class="at">-X</span> DELETE http://localhost:8000/items/123</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<section id="try-it-yourself-hit-a-public-api" class="level3">
<h3 class="anchored" data-anchor-id="try-it-yourself-hit-a-public-api">🧪 Try It Yourself: Hit a Public API!</h3>
<p>You don’t need your own server to practice curl! Try these real APIs:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb41-1"><a href="#cb41-1"></a><span class="co"># 1. Get a random joke</span></span>
<span id="cb41-2"><a href="#cb41-2"></a><span class="ex">curl</span> https://official-joke-api.appspot.com/random_joke</span>
<span id="cb41-3"><a href="#cb41-3"></a><span class="co"># Output: {"setup":"Why did the scarecrow win an award?","punchline":"He was outstanding in his field."}</span></span>
<span id="cb41-4"><a href="#cb41-4"></a></span>
<span id="cb41-5"><a href="#cb41-5"></a><span class="co"># 2. Get your public IP address</span></span>
<span id="cb41-6"><a href="#cb41-6"></a><span class="ex">curl</span> https://api.ipify.org<span class="pp">?</span>format=json</span>
<span id="cb41-7"><a href="#cb41-7"></a><span class="co"># Output: {"ip":"103.xx.xx.xx"}</span></span>
<span id="cb41-8"><a href="#cb41-8"></a></span>
<span id="cb41-9"><a href="#cb41-9"></a><span class="co"># 3. Get GitHub user info</span></span>
<span id="cb41-10"><a href="#cb41-10"></a><span class="ex">curl</span> https://api.github.com/users/torvalds</span>
<span id="cb41-11"><a href="#cb41-11"></a><span class="co"># Shows Linus Torvalds' GitHub profile!</span></span>
<span id="cb41-12"><a href="#cb41-12"></a></span>
<span id="cb41-13"><a href="#cb41-13"></a><span class="co"># 4. Get a random cat fact</span></span>
<span id="cb41-14"><a href="#cb41-14"></a><span class="ex">curl</span> https://catfact.ninja/fact</span>
<span id="cb41-15"><a href="#cb41-15"></a><span class="co"># Output: {"fact":"A cat's brain is...", "length":...}</span></span>
<span id="cb41-16"><a href="#cb41-16"></a></span>
<span id="cb41-17"><a href="#cb41-17"></a><span class="co"># 5. Check if a website is up</span></span>
<span id="cb41-18"><a href="#cb41-18"></a><span class="ex">curl</span> <span class="at">-I</span> <span class="at">-s</span> https://google.com <span class="kw">|</span> <span class="fu">head</span> <span class="at">-1</span></span>
<span id="cb41-19"><a href="#cb41-19"></a><span class="co"># HTTP/2 200  (means it's working!)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<blockquote class="blockquote">
<p>💡 <strong>Pro tip:</strong> Add <code>| jq</code> at the end to pretty-print JSON (install with <code>sudo apt install jq</code>)</p>
</blockquote>
</section>
</section>
<section id="practical-examples" class="level2">
<h2 class="anchored" data-anchor-id="practical-examples">Practical Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb42-1"><a href="#cb42-1"></a><span class="co"># Test your FastAPI server</span></span>
<span id="cb42-2"><a href="#cb42-2"></a><span class="ex">curl</span> http://localhost:8000/</span>
<span id="cb42-3"><a href="#cb42-3"></a><span class="co"># Output: {"message":"Hello, TDS Students! 👋"}</span></span>
<span id="cb42-4"><a href="#cb42-4"></a></span>
<span id="cb42-5"><a href="#cb42-5"></a><span class="co"># Get item with query</span></span>
<span id="cb42-6"><a href="#cb42-6"></a><span class="ex">curl</span> <span class="st">"http://localhost:8000/items/5?q=test"</span></span>
<span id="cb42-7"><a href="#cb42-7"></a><span class="co"># Output: {"item_id":5,"query":"test"}</span></span>
<span id="cb42-8"><a href="#cb42-8"></a></span>
<span id="cb42-9"><a href="#cb42-9"></a><span class="co"># Hit a public API</span></span>
<span id="cb42-10"><a href="#cb42-10"></a><span class="ex">curl</span> https://api.github.com/users/octocat</span>
<span id="cb42-11"><a href="#cb42-11"></a></span>
<span id="cb42-12"><a href="#cb42-12"></a><span class="co"># Download a file</span></span>
<span id="cb42-13"><a href="#cb42-13"></a><span class="ex">curl</span> <span class="at">-o</span> image.jpg https://example.com/image.jpg</span>
<span id="cb42-14"><a href="#cb42-14"></a></span>
<span id="cb42-15"><a href="#cb42-15"></a><span class="co"># Follow redirects</span></span>
<span id="cb42-16"><a href="#cb42-16"></a><span class="ex">curl</span> <span class="at">-L</span> http://github.com</span>
<span id="cb42-17"><a href="#cb42-17"></a></span>
<span id="cb42-18"><a href="#cb42-18"></a><span class="co"># With authentication</span></span>
<span id="cb42-19"><a href="#cb42-19"></a><span class="ex">curl</span> <span class="at">-H</span> <span class="st">"Authorization: Bearer your_token"</span> https://api.example.com/user</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="curl-output-formatting" class="level2">
<h2 class="anchored" data-anchor-id="curl-output-formatting">curl Output Formatting</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb43-1"><a href="#cb43-1"></a><span class="co"># Pretty print JSON (pipe to jq)</span></span>
<span id="cb43-2"><a href="#cb43-2"></a><span class="ex">curl</span> http://localhost:8000/ <span class="kw">|</span> <span class="ex">jq</span></span>
<span id="cb43-3"><a href="#cb43-3"></a></span>
<span id="cb43-4"><a href="#cb43-4"></a><span class="co"># Save response to file</span></span>
<span id="cb43-5"><a href="#cb43-5"></a><span class="ex">curl</span> <span class="at">-o</span> response.json http://localhost:8000/</span>
<span id="cb43-6"><a href="#cb43-6"></a></span>
<span id="cb43-7"><a href="#cb43-7"></a><span class="co"># Only show HTTP status code</span></span>
<span id="cb43-8"><a href="#cb43-8"></a><span class="ex">curl</span> <span class="at">-s</span> <span class="at">-o</span> /dev/null <span class="at">-w</span> <span class="st">"%{http_code}"</span> http://localhost:8000/</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
</section>
<section id="part-6-conceptual-qa" class="level1">
<h1>Part 6: Conceptual Q&amp;A</h1>
<section id="q1-whats-the-difference-between-localhost-and-0.0.0.0" class="level2">
<h2 class="anchored" data-anchor-id="q1-whats-the-difference-between-localhost-and-0.0.0.0">Q1: What’s the difference between localhost and 0.0.0.0?</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│   localhost (127.0.0.1)              0.0.0.0                            │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   Only YOUR machine can access       ALL network interfaces             │
│                                                                          │
│   ┌──────────┐                      ┌──────────┐                        │
│   │ Computer │ ← Only this          │ Computer │ ← This                 │
│   │          │   can connect        │          │                        │
│   └──────────┘                      └────┬─────┘                        │
│                                          │                               │
│                                     ┌────┴────┐                         │
│                                     │ Network │ ← Others can            │
│                                     │ Users   │   connect too           │
│                                     └─────────┘                         │
│                                                                          │
│   Use: Development, testing         Use: When sharing access            │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<p><strong>Example:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb45-1"><a href="#cb45-1"></a><span class="co"># Only you can access</span></span>
<span id="cb45-2"><a href="#cb45-2"></a><span class="ex">uvicorn</span> main:app <span class="at">--host</span> 127.0.0.1 <span class="at">--port</span> 8000</span>
<span id="cb45-3"><a href="#cb45-3"></a></span>
<span id="cb45-4"><a href="#cb45-4"></a><span class="co"># Anyone on network can access</span></span>
<span id="cb45-5"><a href="#cb45-5"></a><span class="ex">uvicorn</span> main:app <span class="at">--host</span> 0.0.0.0 <span class="at">--port</span> 8000</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
<section id="q2-why-cant-i-access-my-local-server-from-another-device" class="level2">
<h2 class="anchored" data-anchor-id="q2-why-cant-i-access-my-local-server-from-another-device">Q2: Why can’t I access my local server from another device?</h2>
<p><strong>Answer:</strong> Multiple reasons:</p>
<ol type="1">
<li><strong>Binding to localhost</strong> - Server only listens on 127.0.0.1</li>
<li><strong>Firewall</strong> - Blocking incoming connections</li>
<li><strong>NAT</strong> - Your router doesn’t forward traffic</li>
</ol>
<p><strong>Solutions:</strong> - Use <code>--host 0.0.0.0</code> to bind to all interfaces - Open port in firewall - Use Ngrok for public access</p>
<hr>
</section>
<section id="q3-whats-the-difference-between-http-and-https" class="level2">
<h2 class="anchored" data-anchor-id="q3-whats-the-difference-between-http-and-https">Q3: What’s the difference between HTTP and HTTPS?</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│              HTTP                              HTTPS                     │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   Port 80                               Port 443                         │
│                                                                          │
│   ┌────────┐  Plain Text  ┌────────┐   ┌────────┐ Encrypted ┌────────┐ │
│   │ Client │ ────────────►│ Server │   │ Client │ ─────────►│ Server │ │
│   └────────┘  "password"  └────────┘   └────────┘  🔒????   └────────┘ │
│                                                                          │
│   Anyone can read!                      Encrypted with TLS/SSL          │
│                                                                          │
│   ❌ Not secure                         ✅ Secure                        │
│   ❌ Data visible                       ✅ Data encrypted                │
│   ❌ No verification                    ✅ Server verified               │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<hr>
</section>
<section id="q4-what-happens-when-you-type-a-url-in-browser" class="level2">
<h2 class="anchored" data-anchor-id="q4-what-happens-when-you-type-a-url-in-browser">Q4: What happens when you type a URL in browser?</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                 WHAT HAPPENS WHEN YOU TYPE google.com                    │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   1. DNS Lookup                                                          │
│      Browser → DNS Server: "What's google.com's IP?"                    │
│      DNS Server → Browser: "142.250.190.46"                             │
│                                                                          │
│   2. TCP Connection                                                      │
│      Browser → Server: SYN (connection request)                         │
│      Server → Browser: SYN-ACK (accepted)                               │
│      Browser → Server: ACK (confirmed)                                  │
│      (This is the "3-way handshake")                                    │
│                                                                          │
│   3. TLS Handshake (for HTTPS)                                          │
│      Exchange encryption keys                                            │
│      Verify server certificate                                           │
│                                                                          │
│   4. HTTP Request                                                        │
│      Browser → Server: GET / HTTP/1.1                                   │
│                                                                          │
│   5. Server Processing                                                   │
│      Server finds resource, processes request                           │
│                                                                          │
│   6. HTTP Response                                                       │
│      Server → Browser: HTTP/1.1 200 OK + HTML                          │
│                                                                          │
│   7. Rendering                                                           │
│      Browser parses HTML, fetches CSS/JS, renders page                  │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<hr>
</section>
<section id="q5-what-is-rest-api" class="level2">
<h2 class="anchored" data-anchor-id="q5-what-is-rest-api">Q5: What is REST API?</h2>
<p><strong>REST</strong> (Representational State Transfer) is an architectural style for APIs.</p>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                        REST PRINCIPLES                                   │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   1. STATELESS                                                           │
│      Each request contains all info needed; server doesn't remember     │
│                                                                          │
│   2. RESOURCE-BASED                                                      │
│      URLs represent resources: /users, /products, /orders               │
│                                                                          │
│   3. HTTP METHODS = ACTIONS                                             │
│      GET = Read, POST = Create, PUT = Update, DELETE = Remove           │
│                                                                          │
│   4. STANDARD STATUS CODES                                              │
│      200 = OK, 404 = Not Found, 500 = Server Error                      │
│                                                                          │
├─────────────────────────────────────────────────────────────────────────┤
│                          RESTFUL URL EXAMPLES                            │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   GET    /users          List all users                                  │
│   POST   /users          Create new user                                 │
│   GET    /users/123      Get user 123                                    │
│   PUT    /users/123      Update user 123                                 │
│   DELETE /users/123      Delete user 123                                 │
│                                                                          │
│   GET    /users/123/orders     Get orders for user 123                  │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<hr>
</section>
<section id="q6-why-do-we-need-ngrok-instead-of-just-using-our-ip" class="level2">
<h2 class="anchored" data-anchor-id="q6-why-do-we-need-ngrok-instead-of-just-using-our-ip">Q6: Why do we need Ngrok instead of just using our IP?</h2>
<p><strong>Answer:</strong></p>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                     WHY NOT JUST USE YOUR IP?                            │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   PROBLEM 1: Private IP                                                  │
│   Your IP (192.168.x.x) is PRIVATE - not accessible from internet       │
│                                                                          │
│   PROBLEM 2: NAT/Router                                                  │
│   Router doesn't know which device to forward requests to               │
│                                                                          │
│   PROBLEM 3: Dynamic IP                                                  │
│   Your public IP changes regularly (unless you pay for static IP)       │
│                                                                          │
│   PROBLEM 4: Firewall                                                    │
│   ISP might block incoming connections                                   │
│                                                                          │
│   PROBLEM 5: No HTTPS                                                    │
│   You'd need SSL certificates for secure connections                     │
│                                                                          │
│   ─────────────────────────────────────────────────────────────────     │
│                                                                          │
│   NGROK SOLVES ALL OF THIS:                                             │
│   ✓ Gives you a public URL                                              │
│   ✓ Handles NAT traversal                                               │
│   ✓ Static subdomain (paid) or random (free)                            │
│   ✓ Bypasses firewalls                                                   │
│   ✓ Free HTTPS included                                                  │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<hr>
</section>
<section id="q7-whats-the-difference-between-synchronous-and-asynchronous-requests" class="level2">
<h2 class="anchored" data-anchor-id="q7-whats-the-difference-between-synchronous-and-asynchronous-requests">Q7: What’s the difference between synchronous and asynchronous requests?</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│            SYNCHRONOUS                        ASYNCHRONOUS              │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   Request 1  ─────────────────►           Request 1  ───►               │
│              WAIT...                       Request 2  ───►              │
│              ◄─────────────────           Request 3  ───►               │
│   Request 2  ─────────────────►                                         │
│              WAIT...                      ◄─── Response 2               │
│              ◄─────────────────           ◄─── Response 1               │
│   Request 3  ─────────────────►           ◄─── Response 3               │
│              WAIT...                                                     │
│              ◄─────────────────                                         │
│                                                                          │
│   TOTAL TIME: 3 seconds                   TOTAL TIME: ~1 second         │
│   (1s + 1s + 1s)                          (all parallel)                │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<p>FastAPI supports async:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb51"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1"></a><span class="at">@app.get</span>(<span class="st">"/items"</span>)</span>
<span id="cb51-2"><a href="#cb51-2"></a><span class="cf">async</span> <span class="kw">def</span> get_items():</span>
<span id="cb51-3"><a href="#cb51-3"></a>    <span class="co"># Can handle multiple requests concurrently</span></span>
<span id="cb51-4"><a href="#cb51-4"></a>    <span class="cf">return</span> {<span class="st">"items"</span>: [...]}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
<section id="q8-how-do-cookies-and-sessions-work" class="level2">
<h2 class="anchored" data-anchor-id="q8-how-do-cookies-and-sessions-work">Q8: How do cookies and sessions work?</h2>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                     COOKIES &amp; SESSIONS                                   │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   1. First Request (Login)                                              │
│                                                                          │
│   Browser ──────────────────────────────────────────────► Server        │
│           POST /login {username, password}                               │
│                                                                          │
│   Server validates, creates session, sends cookie                       │
│                                                                          │
│   Browser ◄────────────────────────────────────────────── Server        │
│           Set-Cookie: session_id=abc123                                  │
│                                                                          │
│   ─────────────────────────────────────────────────────────────────     │
│                                                                          │
│   2. Subsequent Requests                                                 │
│                                                                          │
│   Browser ──────────────────────────────────────────────► Server        │
│           GET /dashboard                                                 │
│           Cookie: session_id=abc123                                      │
│                                                                          │
│   Server looks up session, knows who you are!                           │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<hr>
</section>
</section>
<section id="quick-reference-card" class="level1">
<h1>📋 Quick Reference Card</h1>
<pre><code>┌─────────────────────────────────────────────────────────────────────────┐
│                    NETWORKING CHEAT SHEET                                │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                          │
│   KEY CONCEPTS:                                                          │
│   • IP Address = Computer's address                                      │
│   • Port = Specific service on that computer                            │
│   • DNS = Converts domain names to IPs                                   │
│   • HTTP = Protocol for web communication                               │
│                                                                          │
│   COMMON PORTS:                                                          │
│   22 = SSH | 80 = HTTP | 443 = HTTPS | 8000 = FastAPI                   │
│                                                                          │
│   HTTP METHODS:                                                          │
│   GET = Read | POST = Create | PUT = Update | DELETE = Remove           │
│                                                                          │
│   STATUS CODES:                                                          │
│   2xx = Success | 3xx = Redirect | 4xx = Client Error | 5xx = Server   │
│                                                                          │
│   CURL BASICS:                                                           │
│   curl URL                           # GET request                       │
│   curl -X POST -d '{"key":"value"}' URL  # POST with data              │
│                                                                          │
│   FASTAPI:                                                               │
│   uvicorn main:app --reload --host 0.0.0.0 --port 8000                  │
│                                                                          │
│   NGROK:                                                                 │
│   ngrok http 8000                    # Create tunnel                     │
│                                                                          │
└─────────────────────────────────────────────────────────────────────────┘</code></pre>
<hr>
</section>
<section id="session-summary" class="level1">
<h1>🎯 Session Summary</h1>
<p>✅ <strong>Networking Basics</strong>: IP addresses, ports, DNS, TCP vs UDP<br>
✅ <strong>VM Networking</strong>: NAT, Bridged, Host-Only modes, WSL2 networking<br>
✅ <strong>Client-Server Model</strong>: How the web works, URLs, HTTP cycle<br>
✅ <strong>FastAPI</strong>: Building a simple API server<br>
✅ <strong>Ngrok</strong>: Exposing local server to the internet<br>
✅ <strong>curl</strong>: Making HTTP requests from command line</p>
<hr>
<p><em>End of Session 2: Networking and the Web</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/hrmiitm\.github\.io\/tds\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2026 Hritik Roshan Maurya. All rights reserved.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>